name: Bug report
description: Use this template to report a bug
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to our project. Please fill out the following information to report a bug.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug in detail.
      placeholder: Describe the bug...
      value: ""
